//李四
const COUNT_ADD='COUNT_ADD'
const COUNT_SUB='COUNT_SUB'

//张三
const TODO_ADD='TODO_ADD'
const TODO_SUB='TODO_SUB'

//王五
const SONG_ADD='SONG_ADD'
const SONG_DELETE_ALL='SONG_DELETE_ALL'

const SONG_GET_LIST='SONG_GET_LIST'
const SONG_GET_LIST_QQ='SONG_GET_LIST_QQ'

//获取商品列表
const GOOD_GET_LIST="GOOD_GET_LIST"
const PAY_ADD_LIST="PAY_ADD_LIST"

const DELETE_PAY_LIST="DELETE_PAY_LIST"
const CARTGOODS_NUM_ADD="CARTGOODS_NUM_ADD"//增加商品数量
const CARTGOODS_NUM_SUB="CARTGOODS_NUM_SUB"//减少商品数量
const DELETE_ALL_PAY="DELETE_ALL_PAY"//提交删除所有


export{
    COUNT_ADD,
    COUNT_SUB,
    TODO_ADD,
    TODO_SUB,
    SONG_ADD,
    SONG_DELETE_ALL,
    SONG_GET_LIST,
    SONG_GET_LIST_QQ,
    GOOD_GET_LIST,
    PAY_ADD_LIST,
    DELETE_PAY_LIST,
    CARTGOODS_NUM_ADD,
    CARTGOODS_NUM_SUB,
    DELETE_ALL_PAY

}